apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-service
  labels:
    app: {{ .Release.Name }}-api-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api-service
    spec:
      containers:
        - name: api-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
