apiVersion: v2
name: frontend-service
description: A Helm chart for deploying Frontend services
type: application
version: 0.4.1
appVersion: "1.0.0"
maintainers:
  - name: platform-team
    email: platform@example.com
