apiVersion: v2
name: example-app
description: An example Helm chart for Kubernetes applications
type: application
version: 0.4.0
appVersion: "1.0.3"
maintainers:
  - name: your-name
    email: your-email@example.com
